app/routes.py
import vk_api
import smtplib
import time, random, string, os
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from .models import db, User, Project, StudyGroup, Report, ProjectType, UserStatus, Application, ApplicationStatus, ProjectStatus
from . import db, login_manager
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


main = Blueprint('main', __name__)

vk_session = vk_api.VkApi(token='') ##Ввести токен!!!!

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

@main.route('/')
def index():
    projects = Project.query.all()
    
    return render_template('index.html', projects = projects)

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password'] 
        full_name = request.form['full_name']
        group_id = int(request.form.get('group'))

        existing_user = User.query.filter_by(email=email).first()
        if existing_user:
            return 'Этот email уже используется. Пожалуйста, выберите другой.'
        
        hashed_password = generate_password_hash(password, method='sha256')

        user = User(full_name=full_name, email=email, password=hashed_password, group_id = group_id)

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.index'))
    
    StudyGroups = StudyGroup.query.all()
    return render_template('register.html', groups=StudyGroups)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password'] 
        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            return 'Неправильная почта или пароль'
    return render_template('login.html')

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/dashboard')
@login_required
def dashboard():
    user = current_user

    applications = Application.query.filter_by(user_id=user.id).all()
    projects = [Project.query.get(application.project_id) for application in applications]
    return render_template('cabinet.html',  user=user, projects=projects, applications=applications)

@main.route('/student/<int:student_id>')
@login_required
def student_profile(student_id):
    student = User.query.get_or_404(student_id)
    if student.status != UserStatus.student:
        abort(403)  
    
    applications = Application.query.filter_by(user_id=student.id).all()
    projects = [Project.query.get(application.project_id) for application in applications]
    
    return render_template('student_cabinet.html', student=student, projects=projects)

@main.route('/create_project', methods=['GET', 'POST'])
@login_required
def create_project():

    if request.method == 'POST':
        title = request.form['title']
        
        description = request.form['description']
        poster = request.files['poster']
        photo_url = save_photo(poster)
        
        project_type = request.form['project_type']
        problem = request.form['problem']
        max_participants = request.form['max_participants']
        solution = request.form['solution']
        status = project_status_user[current_user.status.name]
        target_groups = request.form.getlist('target_groups')
        mentors = request.form.getlist('mentors')
        project = Project(title=title, description=description, max_participants=max_participants, project_type = project_type, problem=problem, solution = solution, status=status, poster=photo_url)
        
        db.session.add(project)
        db.session.commit()
        for group_id in target_groups:
            group = StudyGroup.query.get(group_id)
            project.target_groups.append(group)
        
        for mentor_id in mentors:
            mentor = User.query.get(mentor_id)
            project.mentors.append(mentor)

        project.manager_id = current_user.id
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        mentors = User.query.filter_by(status=UserStatus.mentor)
        StudyGroups = StudyGroup.query.all()
        return render_template('create_project.html', groups=StudyGroups, types=ProjectType, mentors=mentors)

@main.route('/project/<int:project_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_project(project_id):
    project = Project.query.get_or_404(project_id)
    
    if current_user.id != project.manager_id:
        abort(403)
    
    all_groups = StudyGroup.query.all()
    all_mentors = User.query.filter(User.status.in_([UserStatus.teacher, UserStatus.mentor])).all()

    if request.method == 'POST':
        project.title = request.form['title']
        project.description = request.form['description']
        project.problem = request.form['problem']
        project.solution = request.form['solution']
        poster = request.files['poster']
        project.poster = save_photo(poster)
        project.max_participants = request.form['max_participants']
        project.target_groups.clear()

        target_group_ids = request.form.getlist('target_groups')
        project.target_groups = StudyGroup.query.filter(StudyGroup.id.in_(target_group_ids)).all()

        mentor_ids = request.form.getlist('mentors')
        project.mentors = User.query.filter(User.id.in_(mentor_ids)).all()

        db.session.commit()
        notify_project_changes(project)
        return redirect(url_for('main.project_detail', project_id=project.id))
    
    return render_template('edit_project.html', project=project, groups =all_groups, mentors = all_mentors)
 
@main.route('/project/<int:project_id>', methods=['GET', 'POST'])
@login_required
def project_detail(project_id):
    project = Project.query.get_or_404(project_id)
    application = Application.query.filter_by(user_id=current_user.id, project_id=project.id).first()
    reports = Report.query.filter_by(project_id=project_id).all()

    if request.method == 'POST':
        if current_user.status == UserStatus.student:
            if application and application.status == ApplicationStatus.accepted:
                if 'report_file' in request.files:
                    report_file = request.files['report_file']
                    if report_file:
                        filename = save_report(report_file)
                        description = request.form.get('description')
                        report = Report(
                            date=datetime.utcnow(),
                            author_id=current_user.id,
                            file=filename,
                            description=description,
                            project_id=project.id
                        )
                        db.session.add(report)
                        db.session.commit()

                        notify_mentors_about_report(project, current_user)

                        return redirect(url_for('main.project_detail', project_id=project.id))
            else:
                application_count = Application.query.filter_by(user_id=current_user.id).count()
                if application_count >= 5:
                    return redirect(url_for('main.project_detail', project_id=project_id))

                existing_application = Application.query.filter_by(user_id=current_user.id, project_id=project_id).first()
                if existing_application:
                    return redirect(url_for('main.project_detail', project_id=project_id))

                priority = request.form['priority']
                new_application = Application(user_id=current_user.id, project_id=project.id, priority=priority)
                db.session.add(new_application)
                db.session.commit()

                return redirect(url_for('main.project_detail', project_id=project_id))

        # Логика для преподавателей и администраторов
        if current_user.status in [UserStatus.teacher, UserStatus.admin]:
            action = request.form.get('action')
            if action == 'approve':
                project.status = ProjectStatus.open_recruitment  
                notify_project_change(project, ProjectStatus.open_recruitment.value)

            elif action == 'reject':
                project.status = ProjectStatus.rejected
                notify_project_change(project, ProjectStatus.rejected.value)

            db.session.commit()
            return redirect(url_for('main.project_detail', project_id=project.id))

    return render_template('project_detail.html', project=project, application=application, reports=reports)

@main.route('/delete_application/<int:application_id>', methods=['POST'])
def delete_application(application_id):
    application = Application.query.get_or_404(application_id)

    if application.user_id != current_user.id:
        return redirect(url_for('main.project_detail', project_id=application.project_id))

    db.session.delete(application)
    db.session.commit()
    return redirect(url_for('main.project_detail', project_id=application.project_id))

@main.route('/application/<int:application_id>/process', methods=['POST'])
@login_required
def process_application(application_id):
    application = Application.query.get_or_404(application_id)
    project_id = application.project_id
    project = Project.query.get_or_404(project_id)

    if current_user.id != project.manager_id and current_user not in project.mentors:
        abort(403)

app/templates/cabinet.html
<h1>Личный кабинет: {{ user.full_name }}</h1>
<p>Email: {{ user.email }}</p>
<p>Группа: {{user.group.name}} - {{user.group.type.value}}{{user.group.year_of_entry}}</p>
{% if user.consent_to_share_competency %}
  <p>Профиль компетенций: {{ user.competency_profile }}</p>
{% endif %}
<h2>Проекты:</h2>
<ul>
  {% for project in projects %}
  <li>
    <a href="{{ url_for('main.project_detail', project_id=project.id) }}">{{ project.title }}</a> - Статус: {{ project.status.value }}
</li>
  {% endfor %}
</ul>
<h2>Заявки:</h2>
<ul>
  {% for app in applications %}
    {% for project in projects %}
    {% if project.id == app.project_id%}
    <li>Проект:<a href="{{ url_for('main.project_detail', project_id=project.id) }}">{{ project.title }}</a> - Статус: {{ app.status.value }}</li>
    {% endif %}
    {% endfor %}
    {% endfor %}
</ul>

app/templates/create_project.html
<!DOCTYPE html>
<html>
<head>
  <title>Добавить товар</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <h1>Добавить проект</h1>
  <form action="/create_project" method="post" enctype="multipart/form-data">
    <label for="title">Название</label>
    <input type="text" name="title" id="title">

    <label for="description">Описание</label>
    <input type="text" name="description" id="description">

    <label for="problem">Проблема</label>
    <input type="text" name="problem" id="problem">

    <label for="solution">Решение</label>
    <input type="text" name="solution" id="solution">
    
    <label for="max_participants">Максимально количество студентов</label>
    <input type="number" name="max_participants" id="max_participants">
    
    <label for="project_type">Тип проекта</label>
    <select name="project_type" id="project_type">
      {% for type in types %}
      <option value="{{ type.name }}">{{ type.value }}</option>
      {% endfor %}  
    </select>
    
    <label for="target_groups">Целевые группы</label>
    <select name="target_groups" id="target_groups" multiple>
      {% for group in groups %}
      <option value="{{ group.id }}">{{group.name}} - {{group.type.value}}{{group.year_of_entry}}</option>
      {% endfor %}  
    </select>

    <label for="mentors">Менторы</label>
    <select name="mentors" id="mentors" multiple>
      {% for mentor in mentors %}
      <option value="{{ mentor.id }}">{{mentor.full_name}}</option>
      {% endfor %}  
    </select>
    
    <label for="poster">Выберите постер:</label><br>
    <div id="poster">
      <input type="file" name="poster" required><br><br>
    </div>

    <input type="submit" value="Добавить проект">
  </form>
</body>
</html>

app/templates/edit_project.html
<form method="post">
    <label for="title">Название</label>
    <input type="text" name="title" value="{{ project.title }}">
    
    <label for="description">Описание</label>
    <textarea name="description">{{ project.description }}</textarea>
    
    <label for="problem">Проблема</label>
    <textarea name="problem">{{ project.problem }}</textarea>
    
    <label for="solution">Решение</label>
    <textarea name="solution">{{ project.solution }}</textarea>

    <label for="max_participants">Максимально количество студентов</label>
    <input type="number" name="max_participants" id="max_participants">
        
    <label for="poster">Выберите постер:</label><br>
    <div id="poster">
      <input type="file" name="poster" required><br><br>
    </div>
    
    <label for="target_groups">Целевые группы</label>
    <select name="target_groups" multiple>
        {% for group in all_groups %}
            <option value="{{ group.id }}" {% if group in project.target_groups %}selected{% endif %}>
                {{ group.name }} - {{ group.type.value }} {{ group.year_of_entry }}
            </option>
        {% endfor %}
    </select>

    <label for="mentors">Менторы</label>
    <select name="mentors" multiple>
        {% for mentor in all_mentors %}
            <option value="{{ mentor.id }}" 
            {% if mentor in project.mentors %}
            selected
            {% endif %}>
                {{ mentor.full_name }}
            </option>
        {% endfor %}
    </select>

    <button type="submit">Сохранить изменения</button>
</form>

app/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <title>Интернет-мастерская</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Интернет-мастерская</a>
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            {% if current_user.status.name == 'admin'%}
            <li class="nav-item">
                <a class="nav-link" href="/create_project">Пользователи</a>
            </li>
            {% endif %}
            {% if current_user.status.name != 'student'%}
            <li class="nav-item">
                <a class="nav-link" href="/create_project">Создать</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="/dashboard">Кабинет</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/logout">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="/register">Регистрация</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/login">Войти</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        <h2>Проекты:</h2>
        <ul>
            {% for project in projects %}
            <li>{{ project.title }} ({{ project.status.value }}) 
                <form method="get" action="{{ url_for('main.project_detail', project_id=project.id) }}">
                    <a>Описание: {{project.description}}</a>
                        <a>Тип проекта: {{project.project_type.value}}</a>
                        <a>Целевые группы: 
                            {% for group in project.target_groups %}
                                {{ group.name }} - {{ group.type.value }} {{ group.year_of_entry }}
                                {% if not loop.last %}, {% endif %}
                            {% endfor %}
                        </a><br>
                        <img src="{{project.poster}}" alt="Product Photo" width="30%">
                        <button type="submit"
                        class="btn btn-primary">Открыть</button></form>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>

</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Вход</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Вход</h1>
        <form method="post" action="/login">
            <div class="form-group">
                <label for="email">Имя пользователя:</label>
                <input type="text" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="password">Пароль:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
</body>
</html>

app/templates/project_detail.html
<h1>{{ project.title }}</h1>
<p>Описание: {{ project.description }}</p>
<p>Тип проекта: {{ project.project_type.value }}</p>
<p>Статус: {{ project.status.value }}</p>
<p>Целевые группы:
    {% for group in project.target_groups %}
        {{ group.name }} - {{ group.type.value }} {{ group.year_of_entry }}
        {% if not loop.last %}, {% endif %}
    {% endfor %}
</p>

<img src="{{ project.poster }}" alt="Poster" width="30%">
<p>Проблема: {{ project.problem }}</p>
<p>Предлагаемое решение: {{ project.solution }}</p>

{% if current_user.status.name == 'student' and project.status.name == 'open_recruitment'%}
    {% if application and application.status.name == 'accepted' %}
        <form action="" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="description">Описание отчета</label>
                <textarea name="description" class="form-control" required></textarea>
            </div>
            <div class="form-group">
                <label for="report_file">Файл отчета</label>
                <input type="file" name="report_file" class="form-control-file" required>
            </div>
            <button type="submit" class="btn btn-primary">Загрузить отчет</button>
        </form>
    {% elif application %}
        <p>Вы уже подали заявку на этот проект.</p>
        <form method="post" action="{{ url_for('main.delete_application', application_id=application.id) }}">
            <button type="submit" class="btn btn-danger">Удалить заявку</button>
        </form>
    {% else %}
        <form method="post">
            <label for="priority">Приоритет</label>
            <input type="number" name="priority" id="priority" min="1" max="5">
            <button type="submit" class="btn btn-success">Оставить заявку</button>
        </form>
    {% endif %}
    
{% elif current_user.id == project.manager_id or current_user in project.mentors %}
    <h2>Заявки на проект</h2>
    <ul>
        {% for application in project.confirmed_applications %}
            <li>
                <a href="{{ url_for('main.student_profile', student_id=application.user_id) }}">{{ application.user.full_name }}</a> 
                - Статус: {{ application.status.value }}
                {% if application.status.name != 'accepted' and application.status.name != 'rejected' %}
                    <form method="post" action="{{ url_for('main.process_application', application_id=application.id) }}">
                        <button type="submit" name="action" value="approve" class="btn btn-success">Подтвердить</button>
                        <button type="submit" name="action" value="reject" class="btn btn-danger">Отклонить</button>
                    </form>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <h3>Отчеты студентов</h3>
    <ul>
        {% for report in reports %}
            <li>
                <strong>{{ report.author_id.full_name }}</strong> — {{ report.date.strftime('%Y-%m-%d') }}<br>
                <p>{{ report.description }}</p>
                <a href="{{ url_for('static', filename='reports/' + report.file) }}" target="_blank">Скачать отчет</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% if current_user.status.name == 'teacher' or current_user.status.name == 'admin' %}
{% if project.status.name == 'not_confirmed' %}
    <h2>Управление проектом</h2>
    <p>Текущий статус проекта: {{ project.status.value }}</p>
        <form method="post" action="{{ url_for('main.project_detail', project_id=project.id) }}">
            <button type="submit" name="action" value="approve" class="btn btn-success">Подтвердить проект</button>
            <button type="submit" name="action" value="reject" class="btn btn-danger">Отклонить проект</button>
        </form>
    {% endif %}
{% endif %}

app/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Регистрация</title>
</head>
<body>
    <h1>Регистрация</h1>
    <form method="POST" action="/register">
        <label for="email">Почта:</label>
        <input type="text" id="email" name="email" required><br><br>

        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required><br><br>

        <label for="full_name">ФИО:</label>
        <input type="text" id="full_name" name="full_name" required><br><br>
        
        <label for="group">Группа</label>
        <select name="group" id="group">
          {% for group in groups %}
          <option value="{{ group.id }}">{{group.name}} - {{group.type.value}}{{group.year_of_entry}}</option>
          {% endfor %}  
        </select>

        <input type="submit" value="Зарегистрироваться">
    </form>
</body>
</html>

app/templates/student_cabinet.html
<h1>Профиль студента: {{ student.full_name }}</h1>
<p>Группа: {{ student.group.name }}</p>
{% if student.consent_to_share_competency %}
  <p>Профиль компетенций: {{ student.competency_profile }}</p>
{% endif %}
<h2>Проекты, на которые поданы заявки:</h2>
<ul>
    {% for project in projects %}
    <li>
        <a href="{{ url_for('main.project_detail', project_id=project.id) }}">{{ project.title }}</a> - Статус: {{ project.status.value }}
    </li>
    {% else %}
    <p>Студент не подал заявки ни на один проект.</p>
    {% endfor %}
  </ul>